### ISSUE TITLE
Als je een REGEX pattroon voor het telefoonnummer specificeert, zorg dan dat je nederlandse nummers kan invoeren

### ISSUE THREAD

**Issue by JeroenHeemskerk** [Corby7/educom-webshop-basis#12]
In de code hieronder specificeer je een regex pattroon bij het 'pattern'-attribuut, dat zegt dat een nummer er altijd zo moet uitzien: `000-00-000`. Maar dit patroon is voor Amerikaanse telefoonnummers, 
https://github.com/Corby7/educom-webshop-basis/blob/ddfc5322e3ea460087d86dd11b1215b90c0eb778/contact.html#L46

Zorg dat je het [patroon voor Nederlandse nummers](https://nl.wikipedia.org/wiki/Telefoonnummer) gebruikt, of gebruik helemaal geen pattern als je de gebruiker vrij wilt laten in welk type telefoon nummer hij wil invoeren.

Nederlandse nummers zijn bijv:
* `06-12345678` (dus een 0 een 6 een streepje en 8 cijfers, waarbij de eerste geen 0 mag zijn)
* `012-3456789` (dus een 0, een cijfer anders dan een 0, nog een cijfer, een streepje en 7 cijfers, waarbij de eerste geen 0 mag zijn)
* `0123-456789` (dus een 0, een cijfer anders dan een 0, nog twee cijfers, een streepje en 6 cijfers, waarbij de eerste geen 0 mag zijn)
* `0031-6-12345678` (zelfde als hierboven maar in plaats van een enkele 0, dus 0031 streepje)
* `0031-12-3456789`
* `0031-123-456789`
* `+31-6-12345678` (zelfde als hierboven maar in plaats van 0031, dus +31)
* `+31-12-3456789`
* `+31-123-456789`
en dan heb je ook mensen die een Belgisch of Duits nummer hebben

**Comment by JeroenHeemskerk** [comment]
Overigens ontstaat het in de HTML zetten je niet van de verantwoordelijkheid, om het ALSNOG in de PHP te checken als je wilt dat mensen een telefoonnummer invoeren dat voldoet aan dit pattroon.

**Comment by Corby7** [comment]
Zag het probleem idd ook net. Ik heb voor nu het pattern attribuut uit html weggehaald.
