### ISSUE TITLE
Er is veel herhaling in de `showMenu` functie, dit is niet D.R.Y.

### ISSUE THREAD

**Issue by JeroenHeemskerk** [Corby7/educom-webshop-basis#22]
In de functie hieronder zit veel herhaling van de `<li><a>` tags
https://github.com/Corby7/educom-webshop-basis/blob/1d162d827c55839c7b502d2fad151a462be89556/index.php#L105-L114

Tip, maak een functie die 1 enkel menu item kan formateren, en geef deze twee parameters `showMenuItem($link, $text)`

De code wordt dan:
```PHP
 function showMenu() { 
     echo ' 
     <nav> 
         <ul>';
     showMenuItem("home", "HOME"); 
     showMenuItem("about", "ABOUT"); 
     showMenuItem("contact", "CONTACT"); 
     echo '
         </ul>  
     </nav>'; 
 } 
```

**Comment by Corby7** [comment]
Hetgeen wat ik hier niet helemaal begrijp is dat ik uiteindelijk meer regels/code kwijt ben aan het opsplitsen van deze ene functie in twee functies. Ook vind ikzelf de readability slechter worden, doordat een simpele list nu weer word verstopt in een andere functie?
Maakt dat ook niet uit voor het schrijven van clean code?
