### ISSUE TITLE
Deze functie doet niets, het kopieert een array

### ISSUE THREAD

**Issue by JeroenHeemskerk** [Corby7/educom-webshop-basis#30]
De code hieronder: 
https://github.com/Corby7/educom-webshop-basis/blob/43cedd4752d01897e96ef94924800259b95ab51b/index.php#L33-L39

Maakt een nieuwe array aan en kopieert iedere value in de gegeven 'array' naar deze nieuwe array. 
De `isset($array[$key])` is namelijk ALTIJD waar omdat je de $keys uit DEZELFDE array gebruikt.

`$default` wordt dus nooit gebruikt.

**Comment by Corby7** [comment]
Klopt, ik gebruikt deze functie ook niet meer. Had al verwijdert moeten zijn.
