### ISSUE TITLE
Mooi dat je compact en extract gebruikt, ik wist niet dat dit kon

### ISSUE THREAD

**Issue by JeroenHeemskerk** [Corby7/educom-webshop-basis#31]
Je gebruikt `compact` en `extract` om variablen van de ene functie over te zetten naar de andere functie, hierdoor hoef je niet $data[$variabele] te gebruiken.  
Dit is really cool. Je bent de eerste student in 5 jaar die dit gebruikt! 

https://github.com/Corby7/educom-webshop-basis/blob/43cedd4752d01897e96ef94924800259b95ab51b/contact.php#L98
https://github.com/Corby7/educom-webshop-basis/blob/43cedd4752d01897e96ef94924800259b95ab51b/contact.php#L121

**Comment by Corby7** [comment]
vet! alles te danken aan google wel :)
